### ISSUE TITLE
Translate German descriptions into English

### ISSUE THREAD

**Issue by pogopaule** [pogopaule/awesome-sustainability-jobs#8]
This project started with a focus on German speaking countries.
Hence the description for companies based in Germany are in German.
Now that this project is getting more and more international the main language should be English.

see e.g. https://github.com/pogopaule/awesome-sustainability-jobs/blob/main/src/data.yaml#L57

**Comment by AnnyWiliams-28** [comment]
I decided that my city lacks a good job search site. You won't believe it, but people here still use newspapers, because our employers don't post vacancies on popular job search sites, it's more convenient for them to advertise in newspapers, which all residents already read.  I can't imagine exactly how this is still possible in the age of such virtual opportunities. But that's not the point. I know how to help you find the answer to your question. I came across an interesting article on the syndicode website and it sounds the same as your question [how to build a job search website](https://syndicode.com/blog/how-to-build-a-job-search-website/), this company is engaged in development in many areas, so they have a lot of experience to share knowledge with those who are interested in creating their own projects. But whether you do this task yourself is up to you, and it will be easiest to do it after you read the article.
